[engine]
chain_name = "VoteChain"
chain_id = 3
endpoint = "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
manager_address = "0x75483a611fd927ca3f0ef314a5594ff61a87e4fc"


[[chains]]
chain_name = "Ropsten"
id = 2 # Self defined
chain_id = 3
chain_type = "ethereum"
vote_chain = true
start_block = 0 # Get the start block from the keystore. If the start block value is 0
endpoint = "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
bridge_address = "0x451e2ede33b13ff00a3d28f8565032553bf2b486"

[[chains]]
chain_name = "Rinkeby"
id = 1 # Self defined
chain_id = 4
chain_type = "ethereum"
vote_chain = false
start_block = 0 # Get the start block from the keystore. If the start block value is 0
endpoint = "https://rinkeby.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
bridge_address = "0xe0bfb4c2cce940591aea447f4ec64880961421f0"

[[chains]]
chain_name = "Tron"
id = 5 # Self defined
chain_id = 6
chain_type = "tron"
vote_chain = false
start_block = 0 # Get the start block from the keystore. If the start block value is 0
endpoint = "https://nile.trongrid.io"
bridge_address = "0xe0bfb4c2cce940591aea447f4ec64880961421f0"


